INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2021-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2021-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2021-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2021-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2021-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2021-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2021-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2021-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2021-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2022-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2022-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2022-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('pedro', 300, '2023-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 300, '2023-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 300, '2023-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2024-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2024-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('roger', 400, '2025-12-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-01-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-02-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-03-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-04-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-05-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-06-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-07-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-08-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-09-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-10-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-11-01');
INSERT INTO public.beitraege (fahrer, betrag, monat) VALUES ('dani', 400, '2025-12-01');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Versicherung AXA (Anteil)', 85.55, 'versicherung', '2021-10-19', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von, notiz) VALUES ('Winterlager RE 1321', 2042.40, 'winterlager', '2021-10-25', 'roger', 'Von Roger privat überwiesen, muss noch beglichen werden');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootkauf Mastercraft X2', 55000, 'sonstiges', '2021-09-05', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('AXA Versicherung', 610, 'versicherung', '2022-02-25', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Verkehrssteuer', 1200, 'verkehrssteuer', '2022-03-07', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('MMC Frühlingsservice RE 1490', 271, 'fruehlingslager', '2022-04-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Vorführen', 130, 'vorfuehren', '2022-05-17', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('2x Öl von Mats', 72, 'material', '2022-07-15', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Winterlager & Service', 3588, 'winterlager', '2022-12-19', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootsplatz', 3600, 'bootsplatz', '2022-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Wake-Surf Schwimmweste (neu)', 89, 'material', '2022-06-14', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Öl (5 Liter)', 86, 'material', '2022-07-27', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Aufstockung Kasse (Steuern & Ausweis)', 96, 'sonstiges', '2022-03-05', 'dani');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Verkehrsamt Wasserfz-Steuer', 1150, 'verkehrssteuer', '2023-02-02', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootsplatz', 3600, 'bootsplatz', '2023-02-02', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('AXA Versicherung', 609, 'versicherung', '2023-03-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Frühlingslager (inkl. U-wasseranstr.)', 1722, 'fruehlingslager', '2023-04-19', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Winterlager', 4571, 'winterlager', '2023-11-13', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Kauf von 5l Öl', 86, 'material', '2023-07-26', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Trichter für Öl (Ali)', 5, 'material', '2023-08-21', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Verkehrsamt Wasserfz-Steuer', 1150, 'verkehrssteuer', '2024-02-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootsplatz X-2', 3600, 'bootsplatz', '2024-02-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('AXA Versicherung', 610, 'versicherung', '2024-03-06', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Frühlingslager (inkl. Abgastest)', 768, 'fruehlingslager', '2024-03-28', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von, notiz) VALUES ('Bootsplatz Nr. 2 (Boot Spiegel 1956)', 1675, 'bootsplatz', '2024-04-01', 'bootskasse', 'Mutterschiff-Platz Seite Seematt');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Verkehrsamt Boot Spiegel', 76, 'verkehrssteuer', '2024-05-29', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootskauf Spiegel (Marco Trutmann)', 50, 'sonstiges', '2024-06-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Schiffskontrolle Boot Spiegel', 40, 'vorfuehren', '2024-07-03', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von, notiz) VALUES ('Bootsplatz X-2 (2025)', 3725, 'bootsplatz', '2024-12-19', 'bootskasse', 'Neu 3725 statt 3600 CHF');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Winterlager & Service', 4152, 'winterlager', '2024-10-07', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Ausweis Simon Diener (Zweites Boot)', 30, 'sonstiges', '2024-05-01', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Möwen-Schreck System', 15, 'material', '2024-05-01', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Blache Zweites Boot (Spiegel)', 20, 'material', '2024-06-01', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('50.- Engel Gutschein Albert Trutmann', 50, 'sonstiges', '2024-11-29', 'roger');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Kontrollschild Nümmerli für Spiegel-Boot', 13, 'sonstiges', '2024-06-01', 'dani');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Boot Spiegel Verkehrssteuern', 26, 'verkehrssteuer', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Verkehrsamt X-2 Wasserfzg-Steuern', 1150, 'verkehrssteuer', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('AXA Versicherung', 610, 'versicherung', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('MMC Frühlingswerft', 2113, 'fruehlingslager', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Vorführen', 130, 'vorfuehren', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Winterlagerpaket', 4166.55, 'winterlager', '2025-11-04', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootsplatz 2025', 3725, 'bootsplatz', '2025-01-01', 'bootskasse');
INSERT INTO public.ausgaben (bezeichnung, betrag, kategorie, datum, bezahlt_von) VALUES ('Bootsplatz Nr. 2 HG', 1675, 'bootsplatz', '2025-01-01', 'bootskasse');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-03-16', 'dani', 1.5, '{"pedro","dani"}', 696, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-03-19', 'roger', 2, '{"roger","pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-03-22', 'dani', 1, '{"dani"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-04-18', 'roger', 1.5, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-05-12', 'roger', 1.5, '{"roger","pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-05-15', 'roger', 3, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-05-17', 'pedro', 1, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-05-26', 'pedro', 2, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-11', 'roger', 4, '{"roger","pedro","dani"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-12', 'roger', 2, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-18', 'pedro', 3, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-19', 'roger', 4, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-20', 'roger', 2, '{"roger","pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-26', 'roger', 5, '{"roger","dani"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-06-29', 'roger', 3, '{"roger","pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-02', 'pedro', 2, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-03', 'roger', 5, '{"roger","dani"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-06', 'roger', 2.5, '{"roger","dani"}', 737.6, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-08', 'pedro', 1.5, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-09', 'dani', 1.5, '{"dani"}', 741, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-11', 'roger', 3, '{"roger","pedro","dani"}', 745.3, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-14', 'roger', 3, '{"roger","pedro","dani"}', 750.8, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-16', 'roger', 3, '{"roger"}', 753.6, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-17', 'roger', 5, '{"roger","dani"}', 757.5, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-18', 'roger', 3, '{"roger","dani"}', 759.8, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-21', 'dani', 3, '{"dani"}', 762.9, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-24', 'roger', 6, '{"roger","dani"}', 768.2, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-25', 'roger', 1.5, '{"roger"}', 769.4, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-27', 'dani', 2.5, '{"dani"}', 772, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-07-31', 'roger', 1, '{"roger","pedro"}', 773.1, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-01', 'roger', 1, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-04', 'roger', 1, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-05', 'pedro', 2, '{"pedro"}', 779.8, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-10', 'roger', 2, '{"roger","pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-12', 'pedro', 2, '{"pedro"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten) VALUES ('2022-08-14', 'roger', 1, '{"roger"}', NULL, '[]');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-05-15', 'pedro', 1, '{"pedro"}', 786, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-03', 'roger', 2.5, '{"roger","dani"}', 789, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-05', 'roger', 2, '{"roger","pedro","dani"}', 791, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-06', 'roger', 0.5, '{"roger","dani"}', 792, '[]', 'Platz-Test');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-08', 'roger', 3.5, '{"roger","dani"}', 795, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-10', 'roger', 4, '{"roger","dani"}', 799, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-13', 'dani', 1, '{"dani"}', 800, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-15', 'pedro', 0.5, '{"pedro"}', 800, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-17', 'roger', 2.5, '{"roger","pedro","dani"}', 802, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-18', 'roger', 3.5, '{"roger","dani"}', 806, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-06-28', 'roger', 3, '{"roger","dani"}', 809, '[]', 'Öl refill (1L)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-06', 'roger', 3.5, '{"roger","pedro","dani"}', 812, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-08', 'roger', 4.5, '{"roger","pedro","dani"}', 816, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-09', 'pedro', 2.5, '{"pedro"}', 818, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-10', 'dani', 1, '{"dani"}', 820, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-15', 'roger', 4, '{"roger","dani"}', 824, '[]', 'Öl refill (0.5L)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-20', 'roger', 3.5, '{"roger","pedro","dani"}', 827, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-22', 'roger', 3, '{"roger","dani"}', 830, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-23', 'roger', 3, '{"roger"}', 833, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-07-31', 'roger', 2, '{"roger"}', 835, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-02', 'roger', 2.5, '{"roger","dani"}', 837, '[]', 'Öl refill (1.5L)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-11', 'roger', 3, '{"roger","dani"}', 840, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-11', 'roger', 2, '{"roger"}', 842, '[]', 'Abends');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-14', 'roger', 2, '{"roger","dani"}', 844, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-15', 'roger', 2, '{"roger"}', 846, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-16', 'roger', 2, '{"roger","dani"}', 848, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-19', 'roger', 3.5, '{"roger","dani"}', 852, '[]', 'Öl refill (0.2L)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-20', 'roger', 2, '{"roger","dani"}', 854, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-21', 'roger', 1, '{"roger"}', 855, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-22', 'dani', 3, '{"dani"}', 859, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-08-23', 'roger', 3, '{"roger","dani"}', 862, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-09-02', 'roger', 1, '{"roger"}', 863, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-09-05', 'dani', 1, '{"dani"}', 864, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-09-06', 'roger', 2, '{"roger","dani"}', 866, '[]', 'Öl refill (1.2L)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-09-09', 'roger', 2, '{"roger","dani"}', 869, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-09-15', 'roger', 2, '{"roger"}', 871, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2023-10-01', 'roger', 1, '{"roger","dani"}', 872, '[]', 'Letzte Fahrt 2023 (Obermatt-Zmittag)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-06-17', 'roger', 1.5, '{"roger","dani"}', 873, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-06-18', 'dani', 1.5, '{"dani"}', 875, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-06-27', 'roger', 1.5, '{"roger","dani"}', 876, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-15', 'roger', 1, '{"roger"}', 877, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-18', 'roger', 2, '{"roger","dani"}', 879, '[]', 'Öl Check');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-20', 'roger', 3, '{"roger","dani"}', 882, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-25', 'roger', 2, '{"roger","dani"}', 884, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-29', 'roger', 2, '{"roger","dani"}', 886, '[]', 'Öl Check');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-07-30', 'dani', 2, '{"dani"}', 888, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-05', 'dani', 2, '{"dani"}', 890, '[]', 'Öl Check');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-06', 'dani', 1, '{"dani"}', 891.5, '[]', 'Öl 0.5 Liter');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-11', 'dani', 1, '{"dani"}', 893, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-12', 'dani', 1, '{"dani"}', 894, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-13', 'dani', 2, '{"dani"}', 896, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-20', 'dani', 1.5, '{"dani"}', 897, '[]', 'Öl Check');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-22', 'roger', 1, '{"roger"}', 899, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-23', 'roger', 1, '{"roger","dani"}', 900, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-24', 'roger', 5, '{"roger","dani"}', 906, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-28', 'roger', 0.5, '{"roger"}', 906, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-29', 'roger', 1, '{"roger"}', 907, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-08-31', 'roger', 1, '{"roger"}', 908, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2024-09-07', 'dani', 3, '{"dani"}', 911, '[]', 'Öl 1 Liter');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-04-14', 'roger', 0, '{"roger","dani"}', 911, '[]', 'Einwassern');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-05-01', 'roger', 0.5, '{"roger"}', 912, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-05-30', 'roger', 1, '{"roger"}', 913, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-05-31', 'dani', 1, '{"dani"}', 914, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-11', 'roger', 1.5, '{"roger","dani"}', 915, '[]', '40 Liter getankt nach 6x Wakesurfen');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-12', 'roger', 1.5, '{"roger","dani"}', 917, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-13', 'dani', 1, '{"dani"}', 918, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-14', 'roger', 1, '{"roger","dani"}', 919, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-21', 'roger', 1.5, '{"roger"}', 920, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-28', 'roger', 1.5, '{"roger"}', 922, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-06-29', 'roger', 2, '{"roger"}', 924, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-07-12', 'roger', 1, '{"roger","dani"}', 925, '[]', 'Öl 0.5L');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-07-20', 'roger', 2, '{"roger","dani"}', 927, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-08-08', 'roger', 1.5, '{"roger","dani"}', 928, '[]', 'Öl check (i.O.)');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-08-09', 'roger', 3.5, '{"roger","dani"}', 932, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-08-10', 'roger', 0.5, '{"roger"}', 933, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-08-12', 'dani', 1.5, '{"dani"}', 934, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-08-15', 'roger', 2.5, '{"roger","dani"}', 937, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-09-08', 'roger', 0.5, '{"roger","dani"}', 937, '[]', 'Boot Vorführung Kt. SZ in Küssnacht');
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-09-20', 'roger', 2, '{"roger","dani"}', 939, '[]', NULL);
INSERT INTO public.nutzungslogs (datum, fahrer, betriebsstunden, teilnehmer, motorstunden_stand, aktivitaeten, notiz) VALUES ('2025-10-02', 'roger', 0, '{"roger","dani"}', 939, '[]', 'Auswassern');
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-06-11', 'roger', 'Hergiswil', 233, 100, NULL);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-06-18', 'pedro', 'Weggis', 148, 64, NULL);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-06-19', 'roger', NULL, 255, 108, NULL);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-06-26', 'dani', NULL, 239, 102, NULL);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-03', 'dani', NULL, 233, 101, 735.1);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-06', 'roger', NULL, 235, 102, 737.6);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-08', 'pedro', NULL, 92, 41, 739.8);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-14', 'pedro', NULL, 264, 114, 746.8);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-16', 'roger', NULL, 201, 89, NULL);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-17', 'roger', NULL, 195, 86, 756.5);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-21', 'dani', NULL, 206, 91, 761.9);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-24', 'roger', NULL, 251, 111, 767.8);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-07-31', 'pedro', NULL, 222, 98, 773.1);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2022-08-05', 'pedro', 'Hergiswil', 229, 103, 779.8);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-06-08', 'roger', 'Hergiswil', 171, 92, 793);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-06-10', 'dani', 'Hergiswil', 159, 86, 798);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-06-17', 'pedro', 'Hergiswil', 149, 81, 802);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-06-28', 'roger', 'Hergiswil', 193, 104, 807);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-06', 'dani', 'Hergiswil', 164, 90, 811);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-08', 'dani', 'Hergiswil', 155, 85, 814);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-09', 'dani', 'Luzern (AVIA)', 128, 67, 819);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-20', 'roger', 'Hergiswil', 195, 105, 824);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-22', 'roger', 'Hergiswil', 214, 115, 829);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-07-23', 'roger', 'Hergiswil', 161, 87, 833);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-08-11', 'roger', 'Hergiswil', 226, 118, 838);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-08-14', 'dani', 'Hergiswil', 235, 121, 844);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-08-19', 'dani', 'Hergiswil', 214, 109, 849);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-08-20', 'roger', 'Hergiswil', 236, 121, 854);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-08-22', 'dani', 'Hergiswil', 177, 91, 858);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-09-02', 'roger', 'Hergiswil', 207, 106, 863);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2023-09-09', 'dani', 'Hergiswil', 211, 108, 868);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-06-25', 'dani', 'Meyer Küssnacht', 91, 50, 875);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-07-17', 'dani', 'Meyer Küssnacht', 77, 43, 877);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-07-20', 'dani', 'Meyer Küssnacht', 82, 46, 879);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-07-25', 'dani', 'Meyer Küssnacht', 105, 58, 884);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-07-29', 'dani', 'Meyer Küssnacht', 102, 57, 886);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-07-30', 'dani', 'Meyer Küssnacht', 110, 61, 888);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-06', 'dani', 'Meyer Küssnacht', 93, 52, 891);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-12', 'dani', 'Meyer Küssnacht', 109, 59, 894);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-20', 'dani', 'Meyer Küssnacht', 99, 55, 897);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-21', 'dani', 'Meyer Küssnacht', 95, 53, 899);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-23', 'dani', 'Meyer Küssnacht', 115, 64, 902);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-08-24', 'dani', 'Luzern Avia', 113, 58, 906);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-09-05', 'dani', 'Meyer Küssnacht', 78, 44, 906);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2024-09-07', 'dani', 'Meyer Küssnacht', 104, 60, 911);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-06-11', 'dani', 'Meyer', 77, 46, 914);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-06-21', 'roger', NULL, 92, 54, 920);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-07-12', 'dani', 'Meyer', 84, 50, 925);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-08-07', 'dani', 'Meyer', 76, 45, 927);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-08-09', 'dani', 'Meyer', 76, 45, 928);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-08-12', 'dani', 'Meyer', 113, 67, 933);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-08-15', 'dani', 'Meyer', 91, 54, 934);
INSERT INTO public.tanken (datum, fahrer, ort, betrag, liter, motorstunden_stand) VALUES ('2025-09-20', 'dani', 'Meyer', 63, 37, 939);
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x50)', 200, 'roger', '2022-06-19', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x50)', 200, 'dani', '2022-06-26', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (3x50)', 150, 'dani', '2022-07-03', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2022-07-06', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'pedro', '2022-07-14', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2022-07-16', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'roger', '2022-07-17', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'dani', '2022-07-21', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'roger', '2022-07-24', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'pedro', '2022-07-31', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste', 100, 'roger', '2022-08-01', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste', 100, 'roger', '2022-08-04', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'pedro', '2022-08-10', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'dani', '2022-07-18', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'dani', '2022-07-27', '50 CHF/Session (2022 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Dank-Beitrag', 20, 'roger', '2023-06-03', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (3x50)', 150, 'roger', '2023-06-08', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Dank-Beitrag', 15, 'roger', '2023-06-10', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-06-17', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Dank-Beitrag', 15, 'roger', '2023-06-28', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-07-15', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-07-22', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (3x50)', 150, 'roger', '2023-07-23', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-07-31', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-08-11', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'roger', '2023-08-15', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'roger', '2023-08-19', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'roger', '2023-09-09', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-06-08', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-06-10', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-06-18', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-07-15', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-07-20', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-08-02', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-08-14', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-08-16', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-08-19', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'dani', '2023-08-22', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x50)', 100, 'dani', '2023-08-23', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 50, 'dani', '2023-09-06', '50 CHF/Session (2023 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x25)', 50, 'roger', '2024-07-20', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x25)', 50, 'roger', '2024-07-29', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x25)', 100, 'roger', '2024-08-22', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 25, 'dani', '2024-06-17', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste', 80, 'dani', '2024-06-18', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x25)', 50, 'dani', '2024-07-18', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 25, 'dani', '2024-07-20', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 25, 'dani', '2024-07-25', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x25)', 100, 'dani', '2024-07-30', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (5x25)', 125, 'dani', '2024-08-05', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x25)', 100, 'dani', '2024-08-06', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (4x25)', 100, 'dani', '2024-08-11', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x25)', 50, 'dani', '2024-08-12', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (3x25)', 75, 'dani', '2024-08-13', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (2x25)', 50, 'dani', '2024-08-20', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Gast', 25, 'dani', '2024-08-23', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (6x25)', 150, 'dani', '2024-08-24', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Diverse Gäste (6x25)', 150, 'dani', '2024-09-07', '25 CHF/10min Wakesurfen (2024 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Surfgelder Juni/Juli zusammengefasst', 125, 'roger', '2025-06-21', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Sarah', 25, 'dani', '2025-05-31', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Fabian', 25, 'dani', '2025-06-11', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Sarah (2x25)', 50, 'dani', '2025-06-12', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Sarah (2x25)', 50, 'dani', '2025-07-20', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Bärtschi, Marisa, Matthias, Sarah', 200, 'dani', '2025-08-09', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Züri, Nadine, Sarah', 100, 'dani', '2025-08-12', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Max, Sarah', 75, 'dani', '2025-08-15', '25 CHF/10min Wakesurfen (2025 Tarif)');
INSERT INTO public.gastsessions (gast_name, betrag, bezahlt_an, datum, notiz) VALUES ('Meli (2x25)', 50, 'dani', '2025-09-20', '25 CHF/10min Wakesurfen (2025 Tarif)');